### ISSUE TITLE
On require, `split': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by zshenker** [rmm5t/iso639#2] opened 2016-03-22 16:49 UTC
Hi,

When using the iso639 gem, upon require, I get the following error. It appears to be when the ISO-639-2_utf-8.txt file is read and the lines are being parsed.

```
2016-03-22_16:46:59.45394 /var/lib/gems/2.2.0/gems/iso639-1.3.0/lib/iso639.rb:40:in `split': invalid byte sequence in US-ASCII (ArgumentError)
2016-03-22_16:46:59.45399 	from /var/lib/gems/2.2.0/gems/iso639-1.3.0/lib/iso639.rb:40:in `block in <module:Iso639>'
2016-03-22_16:46:59.45400 	from /var/lib/gems/2.2.0/gems/iso639-1.3.0/lib/iso639.rb:39:in `each'
2016-03-22_16:46:59.45400 	from /var/lib/gems/2.2.0/gems/iso639-1.3.0/lib/iso639.rb:39:in `<module:Iso639>'
2016-03-22_16:46:59.45401 	from /var/lib/gems/2.2.0/gems/iso639-1.3.0/lib/iso639.rb:31:in `<top (required)>'
2016-03-22_16:46:59.45403 	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
2016-03-22_16:46:59.45403 	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
```

**Comment by rmm5t** [comment] 2016-03-22 18:46
@zshenker Thanks for the report. I cannot reproduce this at the moment. What specific version of ruby are you running this against and what operating system?

Based on the backtrace, my guess is that the file is being opened in US-ASCII instead of UTF-8. I can try to add an explicit `encoding: "utf-8"` while opening the file.

**Comment by zshenker** [comment] 2016-03-22 18:52
@rmm5t Thanks very much for the quick reply.

I am running ruby 2.2.3, on Ubuntu 14.04. It looks like it may be a system language encoding issue:
```
env|grep LANG
LANG=en_US
LANGUAGE=en_US:
```

**Comment by rmm5t** [comment] 2016-03-22 18:53
@zshenker Please try (newly released) v1.3.1 and let me know if the new explicit utf-8 encoding parameter helps your case. Thanks.

**Comment by rmm5t** [comment] 2016-03-23 05:05
Just an update here. I was able to reproduce your original issue by forcing a read in `"us-ascii"` encoding. I'm pretty sure it's safe to close this issue out given the gem now forces an encoding of `"utf-8"` now during the read.

If you concur, please go ahead and close this issue out once you're able to verify against v1.3.1.

Thanks again.

**Comment by rmm5t** [comment] 2016-03-27 16:22
Presuming v1.3.1 adequately fixed this. Please comment if not.

**Closed by rmm5t** 2016-03-27 16:22 UTC

**Comment by zshenker** [comment] 2016-03-28 17:18
Thanks @rmm5t I can confirm that the changes in 1.3.1 have fixed these issues for me.
